'use strict';
function financeVendorExpected(r){return Number(r.basis?.gross_signed??(Number(r.basis?.margin||0)-Number(r.basis?.received||0)))}
function financeMonth(date){return date.slice(0,7)}
function financeShiftMonth(month,delta){const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+delta);return d.toISOString().slice(0,7)}
function financeMonthEnd(month){const d=new Date(financeShiftMonth(month,1)+'-01T00:00:00Z');d.setUTCDate(0);return d.toISOString().slice(0,10)}
function financeVendorReserve(data,asOf,startMonth='2026-08',rate=10){
 const map=Object.fromEntries((data.items||[]).map(r=>[r.item_key,r]));const payments=(data.payments||[]).filter(p=>!p.voided&&p.paid_on<=asOf);
 const receipts=payments.filter(p=>map[p.item_key]?.category==='vendor'&&map[p.item_key]?.direction==='in'&&financeMonth(map[p.item_key].source_month)>=startMonth);
 const received=receipts.reduce((s,p)=>s+Number(p.amount),0),taxPaid=payments.filter(p=>map[p.item_key]?.category==='tax'&&map[p.item_key]?.direction==='out'&&!map[p.item_key]?.basis?.withholding&&p.paid_on>=startMonth+'-01').reduce((s,p)=>s+Number(p.amount),0);
 return {rate:Number(rate),startMonth,received,taxPaid,goal:Math.round(received*Number(rate)/100),remaining:Math.max(Math.round(received*Number(rate)/100)-taxPaid,0),receipts};
}
function financeCompute(data,asOf,month,taxStart=month+'-01',taxEnd=financeMonthEnd(month)){
 const snapshot=data.snapshot,baseDate=snapshot?.snapshot_date||asOf,baseStamp=snapshot?.updated_at||snapshot?.created_at||'',manualTarget=Number(snapshot?.tax_reserve_target||0),saved=Number(snapshot?.tax_reserve_saved||0),buffer=Number(snapshot?.minimum_buffer||0);
 const payments=(data.payments||[]).filter(p=>!p.voided),sumByKey={};payments.forEach(p=>sumByKey[p.item_key]=(sumByKey[p.item_key]||0)+Number(p.gross_amount??(Number(p.amount)+Number(p.income_tax||0)+Number(p.local_tax||0))));
 let items=(data.items||[]).map(r=>{const nativePaid=r.category==='card'&&r.basis?.settled_on?Number(r.amount):0,paid=Math.max(nativePaid,sumByKey[r.item_key]||0),remaining=Math.max(Number(r.amount)-paid,0);return {...r,amount:Number(r.amount),paid,remaining,unknown:!r.confirmed&&r.category!=='card'&&!r.basis?.withholding&&r.due_date<baseDate,overpaid:paid>Number(r.amount)}});
 if(Number(snapshot?.other_upcoming_outflow)>0&&!items.some(r=>r.item_key==='misc:'+snapshot.id))items.push({item_key:'misc:'+snapshot.id,category:'manual',title:'시재에 입력한 기타 예정지출',source_month:financeMonth(baseDate)+'-01',direction:'out',amount:Number(snapshot.other_upcoming_outflow),remaining:Number(snapshot.other_upcoming_outflow),paid:0,due_date:financeMonthEnd(financeMonth(baseDate)),confirmed:true,excluded:false,basis:{formula:'시재의 기타 예정지출 · 다른 항목과 중복 입력 여부 확인'}});
 const itemMap=Object.fromEntries(items.map(r=>[r.item_key,r])),base=Number(snapshot?.total_balance??(Number(snapshot?.bank_balance||0)+Number(snapshot?.cash_on_hand||0)+Number(snapshot?.other_liquid||0)));
 const cashChanges=payments.filter(p=>!p.balance_included&&p.paid_on<=asOf&&(p.paid_on>baseDate||(p.paid_on===baseDate&&p.created_at>baseStamp))).reduce((s,p)=>s+(itemMap[p.item_key]?.direction==='in'?1:-1)*Number(p.amount),0);
 const reserve=financeVendorReserve(data,asOf,financeMonth(snapshot?.reserve_start_month||'2026-08-01'),Number(snapshot?.reserve_rate_pct??10)),vatTarget=Math.max(manualTarget,reserve.remaining),withheldPending=items.filter(r=>r.basis?.withholding&&!r.excluded).reduce((s,r)=>s+r.remaining,0),target=vatTarget+withheldPending;const current=base+cashChanges,free=current-target,eligible=items.filter(r=>!r.excluded&&!r.unknown&&r.remaining>0);
 const forecastRows=eligible.flatMap(r=>{if(r.category!=='payroll'||r.payroll_tax_mode==='none')return [r];const deduction=financePayrollEstimate(r.remaining),taxDue=financeShiftMonth(financeMonth(r.due_date<asOf?asOf:r.due_date),1)+'-10';return [{...r,remaining:r.remaining-deduction.total},{...r,item_key:'forecast-withholding:'+r.item_key,title:r.title+' · 예상 원천세',category:'tax',basis:{withholding:true,projected:true},remaining:deduction.total,amount:deduction.total,due_date:taxDue,projected:true}].filter(x=>x.remaining>0)});
 const totals=(rows)=>({incoming:rows.filter(r=>r.direction==='in').reduce((s,r)=>s+r.remaining,0),outgoing:rows.filter(r=>r.direction==='out').reduce((s,r)=>s+r.remaining,0)});
 const currentMonth=financeMonth(asOf),nextMonth=financeShiftMonth(currentMonth,1),currentEnd=financeMonthEnd(currentMonth),nextEnd=financeMonthEnd(nextMonth);
 const thisRows=forecastRows.filter(r=>r.due_date<=currentEnd),nextRows=forecastRows.filter(r=>financeMonth(r.due_date)===nextMonth),thisTotals=totals(thisRows),nextTotals=totals(nextRows);
 const protectedAt=end=>Math.max(manualTarget,Math.max(reserve.remaining+Math.round(forecastRows.filter(r=>r.category==='vendor'&&r.direction==='in'&&financeMonth(r.source_month)>=reserve.startMonth&&r.due_date<=end).reduce((s,r)=>s+r.remaining,0)*reserve.rate/100)-forecastRows.filter(r=>r.category==='tax'&&!r.basis?.withholding&&r.direction==='out'&&r.due_date<=end).reduce((s,r)=>s+r.remaining,0),0))+items.filter(r=>r.basis?.withholding&&!r.excluded&&r.due_date>end).reduce((s,r)=>s+r.remaining,0)+forecastRows.filter(r=>r.projected&&r.due_date>end&&financeShiftMonth(financeMonth(r.due_date),-1)<=financeMonth(end)).reduce((s,r)=>s+r.remaining,0);
 const endTarget=protectedAt(currentEnd),nextTarget=protectedAt(nextEnd);
 const endCash=current+thisTotals.incoming-thisTotals.outgoing,nextCash=endCash+nextTotals.incoming-nextTotals.outgoing;
 const selected=items.filter(r=>financeMonth(r.due_date)===month),actual=payments.filter(p=>financeMonth(p.paid_on)===month).map(p=>({...p,item:itemMap[p.item_key]}));
 const actualIn=actual.filter(p=>p.item?.direction==='in').reduce((s,p)=>s+Number(p.amount),0),actualOut=actual.filter(p=>p.item?.direction==='out').reduce((s,p)=>s+Number(p.amount),0);
 const salary=selected.filter(r=>r.category==='payroll'&&!r.excluded),salaryGenerated=items.filter(r=>r.category==='payroll'&&financeMonth(r.source_month)===month),salaryPaid=actual.filter(p=>p.item?.category==='payroll').reduce((s,p)=>s+Number(p.amount),0);
 const invoices=(data.invoices||[]).filter(t=>!t.voided&&t.invoice_date>=taxStart&&t.invoice_date<=taxEnd),salesVat=invoices.filter(t=>t.kind==='sales').reduce((s,t)=>s+Number(t.vat_amount),0),purchaseVat=invoices.filter(t=>t.kind==='purchase'&&t.creditable).reduce((s,t)=>s+Number(t.vat_amount),0);
 return {snapshot,base,current,reserve,manualTarget,vatTarget,withheldPending,forecastRows,endTarget,nextTarget,cashChanges,target,saved,buffer,free,items,itemMap,selected,actual,actualIn,actualOut,salary,salaryGenerated,salaryPaid,thisRows,nextRows,thisTotals,nextTotals,endCash,nextCash,endFree:endCash-endTarget,nextFree:nextCash-nextTarget,gap:Math.max(nextTarget+buffer-nextCash,0),unknown:items.filter(r=>r.unknown&&!r.excluded&&r.remaining>0),overpaid:items.filter(r=>r.overpaid),salesVat,purchaseVat,vatReference:Math.max(salesVat-purchaseVat,0),invoices};
}
function financePayrollEstimate(gross){const income=Math.floor(Number(gross)*3/100),local=Math.floor(income/10);return {income,local,total:income+local,net:Number(gross)-income-local}}
if(typeof module!=='undefined'&&module.exports)module.exports={financeCompute,financeShiftMonth,financeMonthEnd,financeVendorReserve,financePayrollEstimate};

const financeState={data:null,model:null,request:0,saving:false,editingKey:null,paymentKey:null,paymentRequest:null,invoiceId:null,evidenceSourceKey:null,filter:'all'};
function financeToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function financeValue(id){return $(id)?.value.trim()||''}
function financeMessage(message,ok=false){const e=$('financeMessage');if(e){e.textContent=message;e.classList.toggle('success',ok)}}
function financeCategory(category){return {vendor:'거래처 정산',payroll:'급여',expense:'비용원장',ad:'광고비',card:'카드 입금',manual:'기타',tax:'세금 납부',payback:'고객 페이백 지급',used:'중고업체 입금'}[category]||category}
function financeSelectOptions(values,value){return values.map(([id,label])=>'<option value="'+esc(id)+'" '+(id===value?'selected':'')+'>'+esc(label)+'</option>').join('')}
async function loadInternalFinance(){
 if(!$('financeMonth'))return;const request=++financeState.request,today=financeToday();if(!$('financeMonth').value)$('financeMonth').value=today.slice(0,7);if(!$('financeTaxStart').value){$('financeTaxStart').value=today.slice(0,4)+(Number(today.slice(5,7))<=6?'-01-01':'-07-01');$('financeTaxEnd').value=today.slice(0,4)+(Number(today.slice(5,7))<=6?'-06-30':'-12-31')}
 const [settlement,receipts]=await Promise.all([sb.rpc('jk_internal_settlement_data',{p_month:financeValue('financeMonth')+'-01',p_as_of:today}),sb.rpc('jk_monthly_customer_receipts',{p_month:financeValue('financeMonth')+'-01'})]);const {data,error}=settlement;if(data)data.customer_receipts=receipts.error?null:receipts.data;if(request!==financeState.request)return;
 if(error||!data){financeMessage('우리 정산을 불러오지 못했습니다. 새로고침해 주세요.');return}const draftBalance=new URLSearchParams(location.search).get('balance');if(!data.snapshot&&draftBalance&&/^\d+$/.test(draftBalance)&&Number.isSafeInteger(Number(draftBalance))){data.snapshot={snapshot_date:today,total_balance:Number(draftBalance),updated_at:new Date().toISOString(),tax_reserve_target:0,tax_reserve_saved:0,tax_reserve_configured:false,draft:true}}financeState.data=data;financeMessage('');renderInternalFinance();
}
function changeFinanceMonth(delta){$('financeMonth').value=financeShiftMonth(financeValue('financeMonth'),delta);loadInternalFinance()}
function renderInternalFinance(){
 if(!financeState.data)return;const today=financeToday(),month=financeValue('financeMonth');if(financeValue('financeTaxStart')>financeValue('financeTaxEnd')){financeMessage('세액 집계 시작일과 종료일을 확인해 주세요.');return}const m=financeCompute(financeState.data,today,month,financeValue('financeTaxStart'),financeValue('financeTaxEnd'));financeState.model=m;
 const text=(id,value)=>{if($(id))$(id).textContent=won(value)};for(const [id,v] of [['financeCurrent',m.current],['financeFree',m.free],['financeProtected',m.target],['financeEnd',m.endCash],['financeNextIn',m.nextTotals.incoming],['financeNextOut',m.nextTotals.outgoing],['financeNextCash',m.nextCash],['financeNextFree',m.nextFree],['financeGap',m.gap],['financeActualIn',m.actualIn],['financeActualOut',m.actualOut],['financeSalaryEarned',m.salaryGenerated.reduce((s,r)=>s+r.amount,0)],['financeSalaryPaid',m.salaryPaid],['financeSalaryPending',m.salary.reduce((s,r)=>s+r.remaining,0)],['financeSalesVAT',m.salesVat],['financePurchaseVAT',m.purchaseVat],['financeVATReference',m.vatReference],['financeTaxSaved',m.saved],['financeTaxGap',Math.max(m.target-m.saved,0)]])text(id,v);
 $('financeBalanceDate').textContent=m.snapshot?'잔고 기준 '+m.snapshot.snapshot_date+' · 이후 기록한 현금 변동 '+won(m.cashChanges):'현재 잔고를 먼저 저장해 주세요.';
 $('financeForecastBasis').textContent='현재 '+today.slice(0,7)+' → 다음 달 '+financeShiftMonth(today.slice(0,7),1)+' · 등록 장부/비용과 미정산 잔액 기준';
 $('financeForecastNote').textContent='이번 달 남은 입금 '+won(m.thisTotals.incoming)+' − 남은 지출 '+won(m.thisTotals.outgoing)+' = 월말 '+won(m.endCash)+'. 다음 달 예상잔고에서 남길 세금 '+won(m.nextTarget)+'을 남기면 '+won(m.nextFree)+'을 사용할 수 있습니다. 추가 판매는 아직 포함하지 않습니다.';
 const warnings=[];if(!m.snapshot)warnings.push('현재 잔고 미입력 · 예상 잔액 계산 전에 합산 잔고를 저장하세요.');if(m.snapshot?.draft)warnings.push('합산 잔고는 임시 계산값입니다. 잔고 / 세금 기준 입력에서 저장해 주세요.');if(!m.snapshot?.tax_reserve_configured)warnings.push('직접 세금 목표 미설정 · 실제 거래처 입금의 '+m.reserve.rate+'% 자동 적립 기준 적용');if(m.unknown.length)warnings.push('기준일 이전 지급·입금 미확인 '+m.unknown.length+'건은 예상에서 제외되어 있습니다. 아래 과거 미확인에서 처리하세요.');if(Number(financeState.data.unclassified_receipts))warnings.push('수납방식 미구분 완납 '+financeState.data.unclassified_receipts+'건 · 장부에서 현금/계좌/카드와 카드 입금예정액을 확인해 주세요.');if(Number(financeState.data.missing_used_dates))warnings.push('중고 판매금액·입금예정일 미확인 '+financeState.data.missing_used_dates+'건 · 중고 반납 / 판매 정산에서 확인하세요.');if(Number(financeState.data.missing_card_dates))warnings.push('카드 입금예정일 미입력 '+financeState.data.missing_card_dates+'건');if(m.overpaid.length)warnings.push('장부 변경으로 이미 지급한 금액이 예정액보다 큰 항목 '+m.overpaid.length+'건');if(m.nextFree<m.buffer)warnings.push('다음 달 세금 확보 후 최소 유지금보다 '+won(m.gap)+' 부족합니다.');$('financeWarnings').textContent=warnings.join('\n');$('financeWarnings').hidden=!warnings.length;
 $('financeMonthLabel').textContent=month+' 지급·입금 정산';$('financeUnknownCount').textContent=m.unknown.length+'건';$('financeSalaryRule').textContent='양수 실리베이트(K−L)의 10% 차감 · 중고 확정 차액 반영 후 판매자별 max(판매월 W 합계, 0) × 그 월의 급여율. 판매월 다음 달 말 지급. '+month+' 발생급여는 '+financeShiftMonth(month,1)+' 지급 대상입니다.';
 $('financeSalaryRows').innerHTML=m.salary.map(r=>'<article class="finance-salary"><b>'+esc(r.basis.staff_name||r.title)+'</b><p>'+esc(financeMonth(r.source_month))+' W '+won(r.basis.margin)+' × '+Number(r.basis.rate||0)+'% = '+won(r.amount)+'</p><p>'+ (r.payroll_tax_mode==='none'?'3.3% 미적용':'사업소득 3.3% · 예상 실수령 '+won(financePayrollEstimate(r.amount).net)+' · 예상 공제 '+won(financePayrollEstimate(r.amount).total))+'</p><p>급여 총액 처리 '+won(r.paid)+' · 미지급 <strong>'+won(r.remaining)+'</strong></p>'+ (r.confirmed&&r.reconciled_ledger_signed!=null&&Number(r.reconciled_ledger_signed)!==Number(r.basis.margin)?'<p class="finance-warning">급여 확정 후 마진이 바뀌었습니다. 현재 자동계산 '+won(r.basis.generated_amount??Math.round(Math.max(Number(r.basis.margin),0)*Number(r.basis.rate)/100))+' · 급여 정산에서 다시 확인하세요.</p>':'')+'<small>'+esc(r.due_date)+' 지급 예정'+(r.confirmed?' · 확정':' · 자동계산')+'</small><button class="btn" data-finance-edit="'+esc(r.item_key)+'">급여 정산</button></article>').join('')||'<p class="finance-help">이 지급월에 등록된 급여가 없습니다. 과거 지급은 정산 항목을 확인하고 실제 지급일로 기록하세요.</p>';
 renderFinanceMoneyFlow();renderFinanceItems();renderFinanceHistory();renderFinanceInvoices();if(typeof renderVendorTaxClose==='function')renderVendorTaxClose();if(typeof initializeSettlementExcel==='function'){initializeSettlementExcel();renderSavedSettlementChecks()}bindFinanceEdit($('financeSalaryRows'));
 // The dashboard uses reconciled cash, while the original cash page retains raw ledger estimates.
 for(const [id,v] of [['dCashAvailable',m.current],['dCashSettlement',m.thisTotals.incoming],['dCashExpenses',m.thisTotals.outgoing],['dCashProjected',m.endFree],['dCashGap',Math.max(m.endTarget+m.buffer-m.endCash,0)]])text(id,v);
 if(!m.snapshot){for(const id of ['financeCurrent','financeFree','financeEnd','financeNextCash','financeNextFree','financeGap','dCashAvailable','dCashProjected','dCashGap'])if($(id))$(id).textContent='잔고 입력 필요';$('financeForecastNote').textContent='현재 통장·현금 합산 잔고를 저장하면 이번 달과 다음 달 예상잔고를 계산합니다.';}if($('dCashExpensesDetail'))$('dCashExpensesDetail').textContent='우리 정산 · 거래처 지급/페이백/급여/비용/광고 미정산';
 if($('dCashGap'))$('dCashGap').style.color=m.endFree<m.buffer?'#dc3f50':'#138754';
}
function financeMoneyFlow(data,m,month){
 const c=data.customer_receipts,actual=m.actual.filter(p=>p.paid_on<=financeToday()),sum=(category,direction)=>actual.filter(p=>p.item?.category===category&&p.item?.direction===direction).reduce((s,p)=>s+Number(p.amount),0);
 const pending=(category,direction)=>m.selected.filter(r=>r.category===category&&r.direction===direction&&!r.excluded&&!r.unknown&&r.remaining>0).reduce((s,r)=>s+r.remaining,0);
 const cardDone=m.items.filter(r=>r.category==='card'&&r.basis?.settled_on&&financeMonth(r.basis.settled_on)===month&&r.basis.settled_on<=financeToday()).reduce((s,r)=>s+r.amount,0);
 return [
  ['고객에게 받은 현금',c?Number(c.cash):null,'판매월 '+month+' · 장부 S 중 현금'],
  ['고객에게 받은 계좌이체',c?Number(c.bank):null,'판매월 '+month+' · 거래처 입금과 별개'],
  ['수납방식 미구분',c?Number(c.unclassified):null,'판매월 '+month+' · 장부에서 수납방식 확인'],
  ['고객 카드 결제금액',c?Number(c.card_charged):null,'판매월 '+month+' · 입금 완료와 별개'],
  ['거래처에서 실제 받은 돈',sum('vendor','in'),'입금일 '+month+' · 직접 기록한 금액'],
  ['거래처에 실제 지급한 돈',sum('vendor','out'),'지급일 '+month+' · 직접 기록한 금액'],
  ['중고업체에서 실제 받은 돈',sum('used','in'),'입금일 '+month+' · 확정 판매가와 별개'],
  ['카드 정산 완료 기록',cardDone,'장부 실제 입금일 '+month+' · 수수료 차감 후'],
  ['고객에게 실제 보낸 페이백',sum('payback','out'),'지급일 '+month+' · 거래처 정산과 별개'],
  ['거래처 아직 받을 돈 / 낼 돈',pending('vendor','in'),'이 달 예정 · 과거 미확인 제외 · 낼 돈 '+won(pending('vendor','out'))],
  ['중고업체 아직 받을 돈',pending('used','in'),'이 달 예정 · 확정 판매금액 − 실제 수령액'],
  ['카드 아직 받을 돈',pending('card','in'),'이 달 예정 · 미입금 정산액']
 ];
}
function renderFinanceMoneyFlow(){const root=$('financeMoneyFlow');if(!root)return;const month=financeValue('financeMonth');$('financeFlowTitle').textContent=month+' 돈 흐름 구분';root.className='finance-kpis';root.innerHTML=financeMoneyFlow(financeState.data,financeState.model,month).map(([label,value,note])=>'<div class="finance-kpi"><span>'+esc(label)+'</span><strong>'+(value===null?'불러오기 실패':won(value))+'</strong><small>'+esc(note)+'</small></div>').join('');}
function bindFinanceEdit(root){root?.querySelectorAll('[data-finance-edit]').forEach(b=>b.onclick=()=>openFinanceItem(b.dataset.financeEdit))}
function renderFinanceItems(){const m=financeState.model;if(!m)return;const filter=financeValue('financeFilter')||'all',rows=filter==='unknown'?m.unknown:m.selected.filter(r=>filter==='all'||r.category===filter);$('financeItems').innerHTML=rows.map(r=>'<article class="finance-item"><div><span class="finance-tag">'+esc(financeCategory(r.category))+'</span> <span class="finance-tag '+(r.direction==='out'?'out':'in')+'">'+(r.direction==='out'?'낼 돈':'받을 돈')+'</span><h4>'+esc(r.title)+'</h4><p>'+esc(r.due_date)+' · '+(r.excluded?'예상에서 제외':r.unknown?'과거 지급 여부 미확인':r.remaining===0?'정산 완료':r.confirmed?'확정 · 미정산':'자동계산 · 확인 필요')+'</p><small>'+esc(r.basis.formula||r.note||'직접 입력')+'</small></div><div class="finance-item-money"><b>'+won(r.amount)+'</b><small>처리 '+won(r.paid)+' · 잔액 '+won(r.remaining)+'</small><button class="btn" data-finance-edit="'+esc(r.item_key)+'">'+(r.category==='card'?'입금일 / 장부 확인':'확인 / 지급 기록')+'</button></div></article>').join('')||'<p class="finance-help">이 조건에 정산할 항목이 없습니다.</p>';bindFinanceEdit($('financeItems'))}
function renderFinanceHistory(){const m=financeState.model;const rows=m.actual;$('financeHistory').innerHTML=rows.map(p=>'<article class="finance-history"><div><b>'+esc(p.item?.title||'정산 기록')+'</b><p>'+esc(p.paid_on)+' · '+esc(p.payment_method)+' · '+esc(p.note||'-')+'</p><small>'+((p.balance_included||p.paid_on<(m.snapshot?.snapshot_date||''))?'기준 잔고에 포함된 지급':'기준 잔고 이후 현금 변동')+'</small>'+ (p.item?.category==='payroll'?'<p>급여 총액 '+won(p.gross_amount??Number(p.amount)+Number(p.income_tax||0)+Number(p.local_tax||0))+' · 소득세 '+won(p.income_tax||0)+' · 지방세 '+won(p.local_tax||0)+'</p>':'')+'</div><div><b>'+won(p.amount)+'</b> <button class="btn" data-payment-void="'+esc(p.id)+'">오입력 취소</button></div></article>').join('')||'<p class="finance-help">이 달에 직접 확인한 지급·입금 기록이 없습니다. 0원은 미기록일 수 있습니다.</p>';$('financeHistory').querySelectorAll('[data-payment-void]').forEach(b=>b.onclick=()=>voidFinancePayment(b.dataset.paymentVoid))}
function renderFinanceInvoices(){const month=financeValue('financeMonth'),rows=(financeState.data.invoices||[]).filter(t=>!t.voided&&financeMonth(t.invoice_date)===month);$('financeInvoices').innerHTML=rows.map(t=>'<article class="finance-history"><div><b>'+esc(t.vendor)+' · '+(t.kind==='purchase'?'매입':'매출')+'</b><p>'+esc(t.invoice_date)+' · 공급가액 '+won(t.supply_amount)+' · 부가세 '+won(t.vat_amount)+'</p><small>'+esc(t.note||'')+(t.kind==='purchase'?(t.creditable?' · 공제가능 확인':' · 공제제외'):'')+'</small></div><button class="btn" data-invoice-edit="'+esc(t.id)+'">수정</button></article>').join('')||'<p class="finance-help">이 달에 확인한 계산서가 없습니다.</p>';$('financeInvoices').querySelectorAll('[data-invoice-edit]').forEach(b=>b.onclick=()=>openFinanceInvoice(b.dataset.invoiceEdit));$('financeLedgerVAT').textContent='선택 판매월 장부 P 부가세 합계 '+won(financeState.data.ledger_vat)+' · 계산서 세액과 별도 참고값';}
function openFinanceBalance(){const s=financeState.model?.snapshot||{},total=financeState.model?.current||0;modalMode='finance-balance';$('modalTitle').textContent='현재 보유한 돈 / 세금 적립';$('modalSave').textContent='잔고 저장';$('modalBody').innerHTML=`<div class="form"><div class="field"><label>기준일</label><input id="fiBalanceDate" type="date" max="${financeToday()}" value="${financeToday()}"></div><div class="field"><label>통장 + 현금 합산 잔고 *</label><input id="fiTotal" inputmode="numeric" value="${esc(String(total))}" oninput="formatMoneyInput(this)"></div><div class="field"><label>직접 부가세·기타 세금 목표 (자동 적립액과 큰 금액 적용)</label><input id="fiTaxTarget" inputmode="numeric" value="${Number(s.tax_reserve_target||0)}" oninput="formatMoneyInput(this)"></div><div class="field"><label>위 잔고 안에서 실제 따로 모아둔 세금</label><input id="fiTaxSaved" inputmode="numeric" value="${Number(s.tax_reserve_saved||0)}" oninput="formatMoneyInput(this)"></div><div class="field"><label>거래처 실제 입금 적립률 (%)</label><input id="fiReserveRate" type="number" min="0" max="100" step="0.1" value="${Number(s.reserve_rate_pct??10)}"></div><div class="field"><label>적립 시작 판매월</label><input id="fiReserveStart" type="month" value="${esc(financeMonth(s.reserve_start_month||'2026-08-01'))}"></div><div class="field"><label>세금 외 최소 유지금</label><input id="fiBuffer" inputmode="numeric" value="${Number(s.minimum_buffer||0)}" oninput="formatMoneyInput(this)"></div><div class="field full"><label>잔고 기준 메모</label><input id="fiBalanceNote" maxlength="5000" value="${esc(s.note||'')}"></div><div class="field full finance-help">이미 받은 현금완납액과 이미 입금된 카드 정산은 이 잔고 안에 포함해 주세요. 실제 모아둔 세금도 합산 잔고에 포함된 돈입니다. 사용 가능액에서는 세금 목표를 한 번만 뺍니다. 사용 가능액에서는 부가세·기타 목표와 미납 원천세를 함께 보호합니다. 이미 납부한 원천세는 다시 보호하지 않습니다.</div></div>`;showModal()}
async function saveFinanceBalance(){if(financeState.saving)return;const date=financeValue('fiBalanceDate'),total=moneyNumber(financeValue('fiTotal')),target=moneyNumber(financeValue('fiTaxTarget')),saved=moneyNumber(financeValue('fiTaxSaved')),buffer=moneyNumber(financeValue('fiBuffer')),rate=Number(financeValue('fiReserveRate')),start=financeValue('fiReserveStart');if(!start||!Number.isFinite(rate)||rate<0||rate>100||!date||date>financeToday()||[total,target,saved,buffer].some(v=>!Number.isSafeInteger(v)||v<0)||saved>total){alert('잔고·세금 금액을 확인해 주세요. 모아둔 세금은 합산 잔고 안의 금액입니다.');return}financeState.saving=true;try{const {error}=await sb.from('jk_internal_balances').upsert({snapshot_date:date,total_balance:total,minimum_buffer:buffer,tax_reserve_target:target,tax_reserve_saved:saved,tax_reserve_configured:true,reserve_rate_pct:rate,reserve_start_month:start+'-01',note:financeValue('fiBalanceNote'),updated_at:new Date().toISOString()},{onConflict:'snapshot_date'});if(error)throw error;closeModal();await loadInternalFinance();toast('합산 잔고와 세금 적립 기준을 저장했습니다.')}catch(e){alert('잔고를 저장하지 못했습니다. '+e.message)}finally{financeState.saving=false}}
function openFinanceItem(key){const r=financeState.model?.itemMap[key];if(!r)return;financeState.editingKey=key;financeState.paymentKey=null;modalMode='finance-item';$('modalTitle').textContent='정산 금액 / 지급 여부 확인';$('modalSave').textContent='확정 내용 저장';$('modalBody').innerHTML=`<div class="finance-help">${esc(r.basis.formula||'직접 입력')} ${r.category==='vendor'?`<br>부가세 포함 정산 예상 ${won(financeVendorExpected(r))}. 고객 페이백·급여·유심·별도 중고입금은 각각 처리합니다. 음수는 거래처에 낼 돈입니다. 계산서 공급가액·부가세는 아래 계산서에서 별도로 기록하며, 정산에 두 번 더하지 않습니다.`:''}${r.category==='payroll'?`<br>${esc(financeMonth(r.source_month))} 판매분 W ${won(r.basis.margin)} × ${Number(r.basis.rate)}%. 확인한 급여 총액을 저장하면 그 금액을 미지급 기준으로 사용합니다.`:''}</div><div class="form"><div class="field full"><label>항목명</label><input id="fiTitle" maxlength="200" value="${esc(r.title)}"></div><div class="field"><label>받을 돈 / 낼 돈</label><select id="fiDirection">${financeSelectOptions([['in','받을 돈'],['out','낼 돈']],r.direction)}</select></div><div class="field"><label>확정 정산 총액 *</label><input id="fiAmount" inputmode="numeric" value="${r.amount}" oninput="formatMoneyInput(this)"></div><div class="field"><label>입금·지급 예정일</label><input id="fiDue" type="date" value="${esc(r.due_date)}"></div>${financeReconciliationFields(r)}<div class="field full"><label>확인 메모 / 계산서 번호</label><textarea id="fiItemNote" maxlength="5000">${esc(r.note||'')}</textarea></div><div class="field full"><label><input id="fiExcluded" type="checkbox" ${r.excluded?'checked':''}> 예상에서 제외 (잔고에 이미 반영된 과거 항목·중복 비용 등)</label></div></div><p class="finance-help">급여·정산 총액 처리 ${won(r.paid)} · 미정산 ${won(r.remaining)}. 과거에 이미 지급한 급여도 실제 지급일로 아래 기록하면 월 지급 내역에 남습니다.</p><button class="btn primary" type="button" onclick="saveFinanceItem(true)">확정 후 실제 ${r.direction==='out'?'지급':'입금'} 기록</button>${r.category==='vendor'?'<button class="btn" type="button" onclick="openFinanceEvidenceFromItem()">계산서 기록</button>':''}`;showModal()}
function beginFinanceManual(){financeState.editingKey='manual:'+crypto.randomUUID();financeState.paymentKey=null;modalMode='finance-manual';$('modalTitle').textContent='기타 지출 / 세금 납부 예정';$('modalSave').textContent='예정 항목 저장';$('modalBody').innerHTML=`<div class="form"><div class="field full"><label>항목명 *</label><input id="fiTitle" maxlength="200" placeholder="예: 부가세 납부, 사무실 보증금, 추가 입금"></div><div class="field"><label>구분</label><select id="fiCategory"><option value="manual">기타</option><option value="tax">세금 납부</option></select></div><div class="field"><label>방향</label><select id="fiDirection"><option value="out">낼 돈</option><option value="in">받을 돈</option></select></div><div class="field"><label>금액 *</label><input id="fiAmount" inputmode="numeric" oninput="formatMoneyInput(this)"></div><div class="field"><label>예정일 *</label><input id="fiDue" type="date" value="${financeMonthEnd(financeValue('financeMonth'))}"></div><div class="field full"><label>메모</label><textarea id="fiItemNote" maxlength="5000"></textarea></div></div><p class="finance-help">거래처 정산, 고객 페이백, 중고 입금, 자동 급여, 비용원장에 이미 들어간 항목은 중복 추가하지 마세요. 원천세는 급여 공제 후 자동 항목이 생깁니다. 수동으로 원천세를 중복 추가하지 마세요. 부가세 납부는 10% 적립 잔액에서 차감되며 직접 목표는 별도 조정해 주세요.</p>`;showModal()}
async function saveFinanceItem(record=false){if(financeState.saving)return;const existing=financeState.model.itemMap[financeState.editingKey],amount=moneyNumber(financeValue('fiAmount')),title=financeValue('fiTitle'),due=financeValue('fiDue');if(!title||!due||!Number.isSafeInteger(amount)||amount<0||amount<(existing?.paid||0)){alert('항목명·날짜·금액을 확인해 주세요. 이미 처리한 금액보다 작게 저장할 수 없습니다.');return}if(record&&$('fiExcluded')?.checked){alert('예상에서 제외한 항목은 지급 기록 대신 제외로 저장해 주세요.');return}if(existing?.paid&&financeValue('fiDirection')!==existing.direction){alert('지급 이력이 있는 항목의 방향은 변경할 수 없습니다.');return}if(existing?.category==='payback'&&(amount!==existing.amount||financeValue('fiDirection')!=='out')){alert('페이백 약정액은 연결 장부에서 수정하세요.');return}if(existing?.category==='used'&&(amount!==existing.amount||financeValue('fiDirection')!=='in')){alert('중고 판매금액은 중고 판매 정산에서 수정하세요.');return}const payload={item_key:financeState.editingKey,category:existing?.category||financeValue('fiCategory')||'manual',title,source_month:existing?.source_month||financeValue('financeMonth')+'-01',direction:financeValue('fiDirection'),amount,due_date:due,excluded:$('fiExcluded')?.checked||false,note:financeValue('fiItemNote'),reconciliation_reason:financeValue('fiDifferenceReason'),reconciled_ledger_signed:existing?.category==='vendor'?financeVendorExpected(existing):existing?.category==='payroll'?Number(existing.basis.margin||0):null,payroll_tax_mode:financeValue('fiPayrollTaxMode')||existing?.payroll_tax_mode||'business33',origin_payment_id:existing?.origin_payment_id||existing?.basis?.source_payment_id||null};if(existing?.category==='vendor'&&((payload.direction==='out'?-amount:amount)!==payload.reconciled_ledger_signed)&&!payload.reconciliation_reason){alert('장부 예상과 거래처 확정액이 다릅니다. 차액 사유를 입력해 주세요.');return}financeState.saving=true;try{let q=sb.from('jk_internal_items');q=existing?.confirmed?q.update(payload).eq('item_key',payload.item_key).eq('updated_at',existing.updated_at):q.insert(payload);const {error,data}=await q.select('*').single();if(error)throw error;await loadInternalFinance();if(record)openFinancePayment(payload.item_key);else{closeModal();toast('정산 확인 내용을 저장했습니다.')}}catch(e){alert(e.code==='PGRST116'?'다른 화면에서 변경된 항목입니다. 새로고침 후 확인해 주세요.':'정산을 저장하지 못했습니다. '+e.message)}finally{financeState.saving=false}}
function openFinancePayment(key){const r=financeState.model.itemMap[key];if(!r||r.remaining<=0){closeModal();toast('이미 전액 정산된 항목입니다.');return}if(r.category==='payback'&&!r.basis.account_verified){alert('페이백 메뉴에서 고객 은행·예금주·계좌번호를 먼저 확인하세요.');return}if(r.category==='payroll'){openFinancePayrollPayment(key);return}financeState.paymentKey=key;financeState.paymentRequest=crypto.randomUUID();modalMode='finance-payment';$('modalTitle').textContent=r.direction==='out'?'실제 지급 기록':'실제 입금 기록';$('modalSave').textContent='실제 처리 기록';$('modalBody').innerHTML=`<h4>${esc(r.title)}</h4><p>미정산 잔액 ${won(r.remaining)}</p>${financePaymentComparison(r)}${r.category==='payback'?'<p class="finance-compare">고객 계좌: '+esc(r.basis.bank_name)+' · '+esc(r.basis.account_holder)+' · '+esc(r.basis.account_number)+'</p>':''}<div class="form"><div class="field"><label>실제 지급·입금일</label><input id="fiPaidOn" type="date" max="${financeToday()}" value="${r.due_date<financeToday()?esc(r.due_date):financeToday()}" onchange="syncFinancePaymentDate()"></div><div class="field"><label>이번 처리 금액 (부분 지급 가능)</label><input id="fiPaidAmount" inputmode="numeric" value="${r.remaining}" oninput="formatMoneyInput(this)"></div><div class="field"><label>수단</label><select id="fiMethod"><option>계좌</option><option>현금</option><option>카드</option><option>기타</option></select></div><div class="field full"><label><input id="fiIncluded" type="checkbox"> 이 금액은 저장한 잔고에 이미 반영됨</label><small>현재 잔고를 기록한 뒤 새로 지급·입금하는 경우 체크하지 마세요. 같은 날 과거 지급을 뒤늦게 적는 경우 체크하세요. 기준일 이전 내역은 잔고에 포함된 것으로 처리합니다.</small></div><div class="field full"><label>처리 메모</label><textarea id="fiPaymentNote" maxlength="5000"></textarea></div></div><p class="finance-help">카드로 비용을 결제했다면 실제 통장 출금일에 기록하세요. 처리 기록을 저장하면 잔액에서 해당 금액만 빠집니다.</p>`;syncFinancePaymentDate();showModal()}
function syncFinancePaymentDate(){const before=financeValue('fiPaidOn')<(financeState.model.snapshot?.snapshot_date||'');$('fiIncluded').disabled=before;if(before)$('fiIncluded').checked=true;else $('fiIncluded').checked=false}
async function saveFinancePayment(){if(financeState.saving)return;if(financeState.model.itemMap[financeState.paymentKey]?.category==='payroll'){await saveFinancePayrollPayment();return}const amount=moneyNumber(financeValue('fiPaidAmount')),date=financeValue('fiPaidOn'),r=financeState.model.itemMap[financeState.paymentKey];if((!financeState.model.snapshot||financeState.model.snapshot.draft)&&date>=financeToday()){alert('오늘 새로 처리한 지급·입금은 현재 합산 잔고를 먼저 저장한 뒤 기록해 주세요. 과거 기록은 실제 과거 날짜로 입력할 수 있습니다.');return}if(!r||!date||date>financeToday()||!Number.isSafeInteger(amount)||amount<=0||amount>r.remaining){alert('실제 날짜와 미정산 잔액 이내의 금액을 입력해 주세요.');return}financeState.saving=true;try{const {error}=await sb.rpc('jk_internal_record_payment',{p_item_key:r.item_key,p_amount:amount,p_paid_on:date,p_request_key:financeState.paymentRequest,p_payment_method:financeValue('fiMethod'),p_balance_included:$('fiIncluded').checked,p_note:financeValue('fiPaymentNote')});if(error)throw error;closeModal();await loadInternalFinance();if(r.category==='payback'){loadPayback();loadAlerts()}if(r.category==='used')loadUsedFinance();toast('실제 정산 내역을 기록했습니다.')}catch(e){alert('기록하지 못했습니다. '+e.message)}finally{financeState.saving=false}}
async function voidFinancePayment(id){if(financeState.saving)return;const note=prompt('잘못 기록한 지급·입금의 취소 사유를 적어주세요.');if(!note?.trim())return;financeState.saving=true;try{const {error}=await sb.rpc('jk_internal_void_payment',{p_id:id,p_note:note.trim()});if(error)throw error;await loadInternalFinance();loadPayback();loadUsedFinance();toast('오입력 기록을 취소하고 미정산 잔액을 복원했습니다.')}catch(e){alert(e.message)}finally{financeState.saving=false}}
function openFinanceInvoice(id=null){const source=modalMode==='finance-item'?financeState.model.itemMap[financeState.editingKey]:null;const r=(financeState.data.invoices||[]).find(t=>t.id===id)||{vendor:source?.category==='vendor'?source.title.split(' · ')[0]:''};financeState.invoiceId=id;modalMode='finance-invoice';$('modalTitle').textContent='계산서 / 부가세 기록';$('modalSave').textContent='계산서 저장';$('modalBody').innerHTML=`<div class="form"><div class="field"><label>작성일</label><input id="fiInvoiceDate" type="date" value="${esc(r.invoice_date||financeToday())}"></div><div class="field"><label>구분</label><select id="fiInvoiceKind">${financeSelectOptions([['purchase','매입 (받은 계산서)'],['sales','매출 (발급한 계산서)']],r.kind||'purchase')}</select></div><div class="field full"><label>연결할 거래처 정산 / 비용</label><select id="fiInvoiceSource" onchange="syncFinanceEvidenceSource()">${financeEvidenceOptions(r.source_item_key||source?.item_key||financeState.evidenceSourceKey||'')}</select></div><div class="field"><label>정산 판매월 / 비용 귀속월</label><input id="fiInvoiceSalesMonth" type="month" value="${esc(r.settlement_sales_month?financeMonth(r.settlement_sales_month):source?.source_month?financeMonth(source.source_month):financeState.evidenceSourceKey?financeMonth(financeState.model.itemMap[financeState.evidenceSourceKey]?.source_month||financeValue('financeMonth')+'-01'):'')}"></div><div class="field"><label>증빙 종류</label><select id="fiEvidenceType">${financeSelectOptions([['tax_invoice','세금계산서'],['card_receipt','카드매출전표'],['cash_receipt','지출증빙 현금영수증'],['receipt','일반영수증 (공제 제외)']],r.evidence_type||'tax_invoice')}</select></div><div class="field full"><label>계산서 승인번호 / 증빙 번호</label><input id="fiInvoiceNumber" maxlength="100" value="${esc(r.invoice_number||'')}"></div><div class="field full"><label>거래처 *</label><input id="fiInvoiceVendor" maxlength="200" value="${esc(r.vendor||'')}"></div><div class="field"><label>공급가액 *</label><input id="fiSupply" inputmode="numeric" value="${Number(r.supply_amount||0)}" oninput="formatMoneyInput(this)"></div><div class="field"><label>계산서 부가세 *</label><input id="fiVAT" inputmode="numeric" value="${Number(r.vat_amount||0)}" oninput="formatMoneyInput(this)"></div><div class="field full"><label><input id="fiCreditable" type="checkbox" ${r.creditable===true?'checked':''}> 매입세액 공제 가능으로 확인함</label></div><div class="field full"><label>메모 / 계산서 번호</label><textarea id="fiInvoiceNote" maxlength="5000">${esc(r.note||'')}</textarea></div>${id?'<div class="field full"><label><input id="fiInvoiceVoid" type="checkbox"> 오입력·취소 계산서 제외</label></div>':''}</div><p class="finance-help">계산서에 적힌 공급가액과 부가세를 입력하세요. 여기서 기록한 계산서 금액은 현금 지출에 다시 더하지 않습니다. 실제 납부액은 과세유형·신고기간·공제 요건 확인이 필요합니다.</p>`;if(!id)syncFinanceEvidenceSource();showModal()}
async function saveFinanceInvoice(){if(financeState.saving)return;const date=financeValue('fiInvoiceDate'),vendor=financeValue('fiInvoiceVendor'),supply=moneyNumber(financeValue('fiSupply')),vat=moneyNumber(financeValue('fiVAT'));if(!date||!vendor||[supply,vat].some(x=>!Number.isSafeInteger(x)||x<0)){alert('작성일·거래처·계산서 금액을 확인해 주세요.');return}financeState.saving=true;try{if($('fiCreditable').checked&&financeValue('fiEvidenceType')==='receipt'&&financeValue('fiInvoiceKind')==='purchase'){alert('일반영수증은 공제가능 확인을 해제해 주세요.');return}const payload={invoice_date:date,kind:financeValue('fiInvoiceKind'),vendor,source_item_key:financeValue('fiInvoiceSource')||null,settlement_sales_month:financeValue('fiInvoiceSalesMonth')?financeValue('fiInvoiceSalesMonth')+'-01':null,invoice_number:financeValue('fiInvoiceNumber'),evidence_type:financeValue('fiEvidenceType'),supply_amount:supply,vat_amount:vat,creditable:$('fiCreditable').checked,note:financeValue('fiInvoiceNote'),voided:$('fiInvoiceVoid')?.checked||false};const existing=financeState.data.invoices.find(t=>t.id===financeState.invoiceId);let q=sb.from('jk_internal_tax_invoices');q=existing?q.update(payload).eq('id',existing.id).eq('updated_at',existing.updated_at):q.insert(payload);const {error}=await q.select('*').single();if(error)throw error;closeModal();await loadInternalFinance();financeState.evidenceSourceKey=null;toast('계산서 세액과 정산 연결을 기록했습니다.')}catch(e){alert(e.code==='23505'?'같은 거래처·유형·증빙 번호가 이미 있습니다. 기존 기록을 확인해 주세요.':'계산서를 저장하지 못했습니다. '+e.message)}finally{financeState.saving=false}}
