const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const repo=path.join(__dirname,'..');
const stub=String.raw`
window.__ledger=[{id:'11111111-1111-4111-8111-111111111111',vendor:'테스트 거래처',activation_date:'2026-09-20',customer_name_snapshot:'테스트 고객',customer_phone_snapshot:'01012345678',cash_received:319000,card_received_amount:0,cash_sale_amount:319000,base_rebate:170000,final_margin:170000,salesperson_id:'22222222-2222-4222-8222-222222222222'}];
window.__writes=[];window.__db={snapshot:{snapshot_date:'2026-10-02',updated_at:'2026-10-02T00:00:00Z',total_balance:1000000,reserve_rate_pct:10},items:[{item_key:'vendor-sep',category:'vendor',title:'테스트 거래처 · 2026-09 판매분',source_month:'2026-09-01',direction:'out',amount:149000,due_date:'2026-10-31',confirmed:false,basis:{margin:170000,received:319000,gross_signed:-149000}}],payments:[],invoices:[],vendor_checks:[],payroll_reports:[]};
function query(table){let filters=[],op='',payload,options,single=false;const q=new Proxy({}, {get:(t,k)=>{if(k==='then')return resolve=>{let data=table==='jk_sales_ledger'?__ledger.filter(r=>filters.every(f=>f(r))):table==='jk_internal_items'?__db.items.filter(r=>filters.every(f=>f(r))):[];if(op==='upsert'){const old=__db.items.find(r=>r.item_key===payload.item_key);if(old)return resolve({data:null,error:{code:'PGRST116',message:'already saved'}});data={...payload,confirmed:true,basis:{},updated_at:new Date().toISOString()};__db.items.push(data);__writes.push({table,payload})}if(op==='update'){data=data[0];if(!data)return resolve({data:null,error:{code:'PGRST116',message:'conflict'}});Object.assign(data,payload,{updated_at:new Date().toISOString()});__writes.push({table,payload})}resolve({data:single?(Array.isArray(data)?data[0]||null:data):data,error:null})};return(...a)=>{if(['upsert','update'].includes(k)){op=k;payload=a[0];options=a[1]}if(k==='eq')filters.push(r=>r[a[0]]===a[1]);if(['single','maybeSingle'].includes(k))single=true;return q}}});return q}
window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>{}},from:query,rpc:async(n,p)=>{if(n==='jk_internal_settlement_data')return {data:structuredClone(__db),error:null};if(n==='jk_customer_receipt_data')return {data:{rows:[],cash_delta:0,actual_customer_in:0},error:null};if(n==='jk_internal_record_payment'){const r=__db.items.find(r=>r.item_key===p.p_item_key);const paid=__db.payments.filter(x=>x.item_key===r.item_key&&!x.voided).reduce((s,x)=>s+x.amount,0);if(p.p_amount>r.amount-paid)return {data:null,error:{message:'overpaid'}};const prev=__db.payments.find(x=>x.request_key===p.p_request_key);if(prev)return {data:prev.id,error:null};const id=crypto.randomUUID();__db.payments.push({id,request_key:p.p_request_key,item_key:r.item_key,amount:p.p_amount,paid_on:p.p_paid_on,payment_method:p.p_payment_method,balance_included:p.p_balance_included,note:p.p_note,created_at:new Date().toISOString()});return {data:id,error:null}}if(n==='jk_internal_void_payment'){Object.assign(__db.payments.find(x=>x.id===p.p_id),{voided:true,void_note:p.p_note});return {data:null,error:null}}return {data:null,error:null}}})};`;
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:1400,height:1000},timezoneId:'Asia/Seoul'}),errors=[],dialogs=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());d.accept(d.type()==='prompt'?'테스트 취소':'')});await page.clock.install({time:new Date('2026-10-02T04:00:00Z')});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.href.includes('supabase-js'))return r.fulfill({contentType:'application/javascript',body:stub});const f=path.join(repo,u.pathname.slice(1));if(u.hostname==='company.test'&&fs.existsSync(f)&&fs.statSync(f).isFile())return r.fulfill({contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(f)});return r.fulfill({status:404,body:''})});
 await page.goto('https://company.test/business-center.html');await page.evaluate(async()=>{hideLogin();state.staff=[{id:'22222222-2222-4222-8222-222222222222',name:'송훈',active:true}];go('finance');await loadInternalFinance()});
 await page.getByRole('button',{name:'+ 현대카드 / 사무실 카드 기록'}).click();await page.locator('#ccLedger').selectOption('11111111-1111-4111-8111-111111111111');
 assert.equal(await page.locator('#ccName').inputValue(),'테스트 고객');assert.equal(await page.locator('#ccCash').inputValue(),'319,000');assert.equal(await page.locator('#ccPhone').inputValue(),'010-1234-5678');assert.equal(await page.locator('#ccCard').inputValue(),'현대카드');
 await page.locator('#ccAmount').fill('319000');await page.locator('#ccCharged').fill('2026-09-20');await page.locator('#modalSave').click();assert.match(dialogs.pop(),/출금 예정일/);
 await page.locator('#ccDue').fill('2026-11-12');await page.locator('#ccMemo').fill('<img src=x onerror=alert(1)>');await page.locator('#ccPayAfter').check();await page.locator('#modalSave').click();await page.waitForFunction(()=>modalMode==='finance-payment'&&!companyCardState.saving,null,{timeout:5000}).catch(async e=>{throw new Error(JSON.stringify({dialogs,errors,state:await page.evaluate(()=>({mode:modalMode,saving:companyCardState.saving,db:__db,inputs:[...document.querySelectorAll('#modalBody input,#modalBody select')].map(x=>[x.id,x.value])}))}))});
 assert(await page.locator('#fiIncluded').isChecked());assert.equal(await page.locator('#fiPaidOn').inputValue(),'');assert.equal(await page.locator('#financeCurrent').textContent(),'1,000,000원');assert.equal(await page.locator('#financeNextOut').textContent(),'319,000원');
 assert.equal(await page.evaluate(()=>__db.items.find(r=>r.item_key==='vendor-sep').amount),149000);assert.equal(await page.evaluate(()=>__ledger[0].final_margin),170000);assert.equal(await page.locator('#companyCardRows img').count(),0);
 await page.locator('#fiPaidOn').fill('2026-10-02');assert(await page.locator('#fiIncluded').isChecked());await page.locator('#fiPaidAmount').fill('100000');await page.locator('#modalSave').click();await page.waitForFunction(()=>__db.payments.length===1&&!financeState.saving&&!document.getElementById('modalBg').classList.contains('show'));
 assert.equal(await page.locator('#financeCurrent').textContent(),'1,000,000원');assert.equal(await page.locator('#financeNextOut').textContent(),'219,000원');assert.match(await page.locator('#companyCardRows').textContent(),/실제 납부/);
 await page.locator('[data-company-pay]').click();await page.locator('#fiPaidOn').fill('2026-10-02');await page.locator('#fiPaidAmount').fill('19000');await page.locator('#fiIncluded').uncheck();await page.locator('#modalSave').click();await page.waitForFunction(()=>__db.payments.length===2&&!financeState.saving&&!document.getElementById('modalBg').classList.contains('show'));assert.equal(await page.locator('#financeCurrent').textContent(),'981,000원');assert.equal(await page.locator('#financeNextOut').textContent(),'200,000원');
 await page.locator('[data-company-edit]').click();await page.locator('#ccAmount').fill('100000');await page.locator('#modalSave').click();assert.match(dialogs.pop(),/이미 납부한 금액/);await page.evaluate(()=>closeModal());
 const key=await page.evaluate(()=>__db.items.find(x=>x.item_key.startsWith('manual:company-card:')).item_key);await page.evaluate(()=>voidFinancePayment(__db.payments[1].id));assert.equal(await page.locator('#financeCurrent').textContent(),'1,000,000원');assert.equal(await page.locator('#financeNextOut').textContent(),'219,000원');
 const persisted=await page.evaluate(()=>structuredClone(__db));await page.reload();await page.evaluate(async db=>{__db=db;hideLogin();state.staff=[{id:'22222222-2222-4222-8222-222222222222',name:'송훈',active:true}];go('finance');await loadInternalFinance()},persisted);
 // The simulated server survives the page reload; no browser storage is used by the feature.
 assert.match(await page.locator('#companyCardRows').textContent(),/테스트 고객/);assert.equal(await page.locator('#financeNextOut').textContent(),'219,000원');
 for(const width of [360,390,768]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await page.locator('[data-company-edit]').first().click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await page.evaluate(()=>closeModal())}
 assert.deepEqual(errors,[]);assert(!await page.evaluate(()=>__writes.some(w=>w.table==='jk_sales_ledger')));console.log('PASS: office Hyundai-card/ledger link, input validation, persisted metadata, vendor and W unchanged, future due date, already-spent cash not deducted twice, new cash outflow once, partial/void payments and mobile');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
