const fs=require('fs'),path=require('path'),assert=require('assert/strict'),vm=require('vm');
const {chromium}=require('playwright');const repo=path.join(__dirname,'..'),output=process.env.TEST_OUTPUT_DIR||require('os').tmpdir();
const stub=String.raw`
window.__staff=[{id:'s1',name:'송훈',active:true},{id:'s2',name:'인성',active:true}];window.__db=[];window.__history=[];window.__writes=[];window.__failNext=false;window.__delay=0;window.__serial=0;
function makeQuery(table){const filters=[];let op='select',payload,one=false,start=0,end=Infinity,count=false;
const q=new Proxy({}, {get:(t,k)=>{if(k==='then')return async resolve=>{await new Promise(r=>setTimeout(r,window.__delay));let rows=table==='jk_consultations'?window.__db:table==='jk_consultation_history'?window.__history:table==='jk_staff'||table==='jk_consultation_staff_directory'?window.__staff:[];const match=r=>filters.every(f=>f(r));let result=rows.filter(match);
if(op!=='select'){window.__writes.push({table,op,payload:JSON.parse(JSON.stringify(payload))});if(window.__failNext){window.__failNext=false;return resolve({data:null,error:{code:'500',message:'test failure'}})}
if(op==='insert'){if(payload.public_request_key&&rows.some(r=>r.public_request_key===payload.public_request_key))return resolve({error:{code:'23505'}});const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const r={id:crypto.randomUUID(),active:true,status:'상담전',followup_days:3,consulted_on:today,next_contact_on:today,consultation_note:'',customer_note:'',last_contact_note:'',...payload,created_at:new Date().toISOString(),updated_at:String(++window.__serial)};rows.push(r);result=[r];}
if(op==='update'){result.forEach(r=>{Object.assign(r,payload);if(['계약완료','종료'].includes(r.status))r.next_contact_on=null;r.updated_at=String(++window.__serial)})}
if(!result.length)return resolve({data:null,error:{code:'PGRST116',message:'conflict'}});if(table==='jk_consultations')result.forEach(r=>window.__history.unshift({consultation_id:r.id,action:payload.last_contacted_at?'재연락 기록':op==='insert'?'상담 등록':'상담 정보 수정',note:payload.last_contact_note||payload.consultation_note||'',snapshot:{staff_name:r.staff_name,status:r.status,next_contact_on:r.next_contact_on},created_at:new Date().toISOString()}));}
const total=result.length;result=result.slice(start,end);return resolve({data:one?(result[0]?JSON.parse(JSON.stringify(result[0])):null):JSON.parse(JSON.stringify(result)),error:one&&!result[0]?{code:'PGRST116'}:null,count:total});};
return (...a)=>{if(k==='select')count=!!a[1]?.count;if(k==='insert'||k==='update'){op=k;payload=a[0]}if(k==='single'||k==='maybeSingle')one=true;if(k==='eq')filters.push(r=>r[a[0]]===a[1]);if(k==='is')filters.push(r=>(r[a[0]]??null)===a[1]);if(k==='in')filters.push(r=>a[1].includes(r[a[0]]));if(k==='lte')filters.push(r=>r[a[0]]!=null&&r[a[0]]<=a[1]);if(k==='ilike'){const needle=a[1].replace(/%/g,'').replace(/\\([%_])/g,'$1').toLowerCase();filters.push(r=>String(r[a[0]]||'').toLowerCase().includes(needle))}if(k==='range'){start=a[0];end=a[1]+1}if(k==='limit')end=a[0];return q;};}});return q;}
window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>{}},from:makeQuery,rpc:async()=>({data:null,error:null})})};`;
(async()=>{
new vm.Script(stub);
for(const f of ['business-consultations.js'])new vm.Script(fs.readFileSync(path.join(repo,f),'utf8'));
for(const f of ['business-center.html','consultation.html'])for(const m of fs.readFileSync(path.join(repo,f),'utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1]);
const browser=await chromium.launch({headless:true,channel:process.env.CHROMIUM_CHANNEL||'msedge'}),context=await browser.newContext({viewport:{width:1400,height:980},timezoneId:'Asia/Seoul'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.href.includes('supabase-js'))return route.fulfill({contentType:'application/javascript',body:stub});const f=path.join(repo,u.pathname.slice(1));if(u.hostname==='consult.test'&&fs.existsSync(f)&&fs.statSync(f).isFile())return route.fulfill({contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(f,'utf8')});return route.fulfill({status:404,body:''})});
await page.goto('https://consult.test/business-center.html');
await page.evaluate(()=>{hideLogin();state.staff=window.__staff;const today=consultToday();window.__db=Array.from({length:42},(_,i)=>({id:crypto.randomUUID(),customer_name:i===0?'<img src=x onerror=alert(1)>':'테스트고객'+(i+1),phone_digits:'010'+String(12340000+i),staff_name:i===41?null:i%2?'인성':'송훈',services:['휴대폰'],contact_method:'전화',intake_source:'직접기록',consulted_on:today,visited_on:today,followup_days:3,next_contact_on:today,status:'재연락',consultation_note:'기기 조건 비교 중',customer_note:'희망 기종 문의',created_at:new Date().toISOString(),updated_at:String(i+100)}));go('consultations')});
await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='42건');
assert.equal(await page.locator('.consult-item').count(),20);await page.locator('#consultNext').click();await page.waitForFunction(()=>document.getElementById('consultPageText').textContent==='2 / 3쪽');
await page.getByRole('tab',{name:'송훈',exact:true}).click();await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='21건');assert.equal(await page.locator('#consultScope').textContent(),'송훈 상담 페이지');
await page.getByRole('tab',{name:'인성',exact:true}).click();await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='20건');
await page.getByRole('tab',{name:'미지정',exact:true}).click();await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='1건');
await page.getByRole('tab',{name:'송훈',exact:true}).click();await page.locator('#consultSearch').fill('010-1234-0000');await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='1건');assert.equal(await page.locator('#consultList img').count(),0);
await page.locator('.consult-item').first().click();await page.waitForSelector('#consultMemo');assert.equal(await page.locator('#consultDetail img').count(),0);assert.equal(await page.locator('#consultPhone').inputValue(),'010-1234-0000');assert.match(await page.locator('.consult-phone').getAttribute('href'),/^tel:010/);
await page.evaluate(()=>loadConsultReminders(false));assert.equal(await page.locator('[data-consult-badge]').first().textContent(),'42');assert.equal(await page.locator('#consultDashboardReminders .consult-reminder').count(),5);assert.equal(await page.locator('#consultAlertReminders .consult-reminder').count(),20);
await page.locator('#consultSearch').fill('');await page.waitForFunction(()=>document.getElementById('consultCount').textContent==='21건');
await page.getByRole('button',{name:'+ 상담 기록',exact:true}).click();await page.locator('#consultName').fill('놓친 고객');await page.locator('#consultPhone').pressSequentially('01098765432');await page.locator('#consultDays').selectOption('5');
const today=await page.evaluate(()=>consultToday()),expected=await page.evaluate(()=>consultAddDays(consultToday(),5));assert.equal(await page.locator('#consultDue').inputValue(),expected);assert.equal(await page.locator('#consultStaff').inputValue(),'송훈');
await page.locator('#consultSave').click();assert.match(await page.locator('#consultMessage').textContent(),/상담내역/);
await page.locator('#consultMemo').fill('가격 비교 중으로 놓친 고객. 5일 뒤 다시 연락');await page.evaluate(()=>{saveConsultDraft();consultState.creating=false;beginNewConsultation(false)});assert.equal(await page.locator('#consultPhone').inputValue(),'010-9876-5432');assert.equal(await page.locator('#consultDays').inputValue(),'5');
await page.evaluate(()=>{window.__delay=20;saveConsultation();saveConsultation()});await page.waitForFunction(()=>document.getElementById('consultMessage').textContent.includes('저장했습니다'));const insert=await page.evaluate(()=>window.__writes.filter(w=>w.op==='insert'));assert.equal(insert.length,1);assert.equal(insert[0].payload.phone_digits,'01098765432');assert.equal(insert[0].payload.next_contact_on,expected);
assert.match(await page.locator('#consultHistory').textContent(),/상담 등록/);await page.locator('#consultContactNote').fill('부재중, 다시 안내 예정');await page.locator('#consultDays').selectOption('4');await page.locator('#consultContactDone').click();await page.waitForFunction(()=>document.getElementById('consultMessage').textContent.includes('연락 결과를 기록'));assert.equal(await page.locator('#consultDue').inputValue(),await page.evaluate(()=>consultAddDays(consultToday(),4)));assert.match(await page.locator('#consultHistory').textContent(),/부재중/);
await page.locator('#consultStatus').selectOption('계약완료');assert(await page.locator('#consultDue').isDisabled());await page.locator('#consultSave').click();await page.waitForFunction(()=>document.getElementById('consultMessage').textContent.includes('저장했습니다'));assert.equal(await page.evaluate(()=>consultState.selected.next_contact_on),null);
await page.locator('#consultStatus').selectOption('재연락');assert.notEqual(await page.locator('#consultDue').inputValue(),'');await page.locator('#consultSave').click();await page.waitForFunction(()=>document.getElementById('consultMessage').textContent.includes('저장했습니다'));
// Optimistic conflict keeps the user's edits visible and does not overwrite newer data.
await page.evaluate(()=>window.__db.find(r=>r.id===consultState.selected.id).updated_at='changed-elsewhere');await page.locator('#consultMemo').fill('새 메모');await page.locator('#consultSave').click();await page.waitForFunction(()=>document.getElementById('consultMessage').textContent.includes('다른 화면'));assert.equal(await page.locator('#consultMemo').inputValue(),'새 메모');
await page.screenshot({path:path.join(output,'jk-consultations-desktop.png'),fullPage:true});
for(const width of [360,390,768]){await page.setViewportSize({width,height:844});assert(!(await page.locator('#consultListPanel').isVisible()));assert(await page.locator('#consultDetail').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));}
await page.screenshot({path:path.join(output,'jk-consultations-mobile.png'),fullPage:true});await page.locator('.consult-mobile-back').click();await page.waitForFunction(()=>!document.getElementById('consultLayout').classList.contains('detail-open'));assert(await page.locator('#consultListPanel').isVisible());
// Add through actual settings, then see the new consultant in every internal choice.
await page.setViewportSize({width:1400,height:980});await page.evaluate(()=>{loadPayrollSettings=async()=>{};loadNotificationStatus=async()=>{};go('settings')});await page.waitForFunction(()=>document.getElementById('setStaff').textContent.includes('송훈'));
await page.locator('#newStaff').fill('추가 담당자');await page.locator('#newStaff').locator('..').getByRole('button',{name:'추가',exact:true}).click();await page.waitForFunction(()=>document.getElementById('setStaff').textContent.includes('추가 담당자'));
await page.evaluate(()=>{window.__staff.at(-1).active=true;state.staff=window.__staff;go('consultations')});await page.getByRole('tab',{name:'추가 담당자',exact:true}).click();await page.getByRole('button',{name:'+ 상담 기록',exact:true}).click();assert.equal(await page.locator('#consultStaff').inputValue(),'추가 담당자');
assert.equal(new URL(await page.evaluate(()=>consultationPublicUrl('추가 담당자'))).searchParams.get('staff'),'추가 담당자');
// Preserve the original assigned name while no longer offering it for new records.
await page.evaluate(()=>{window.__staff.at(-1).active=false;state.staff=window.__staff;renderConsultDetail({customer_name:'과거 고객',phone_digits:'01000000000',staff_name:'추가 담당자',status:'재연락',consulted_on:consultToday(),next_contact_on:consultToday(),followup_days:3},false);renderConsultTabs()});assert.equal(await page.locator('#consultStaff').inputValue(),'추가 담당자');assert.match(await page.locator('#consultStaff option:checked').textContent(),/사용 중지/);assert(await page.getByRole('tab',{name:'추가 담당자 (사용 중지)',exact:true}).isVisible());await page.evaluate(()=>{consultState.staff='all';beginNewConsultation(false)});assert.equal(await page.locator('#consultStaff option[value="추가 담당자"]').count(),0);
// Public list loads from the safe directory and supports arbitrary active names.
await page.goto('https://consult.test/consultation.html?staff='+encodeURIComponent('새 담당자'));await page.evaluate(async()=>{window.__staff.push({id:'s3',name:'새 담당자',active:true},{id:'s4',name:'중지 담당자',active:false});await loadRequestStaff()});assert.equal(await page.locator('#requestStaff').inputValue(),'새 담당자');assert.equal(await page.locator('#requestStaff option[value="중지 담당자"]').count(),0);
await page.goto('https://consult.test/business-center.html');await page.evaluate(()=>{state.staff=window.__staff});
const link=await page.evaluate(()=>consultationPublicUrl('인성'));assert.equal(new URL(link).searchParams.get('staff'),'인성');
await page.goto('https://consult.test/consultation.html?staff='+encodeURIComponent('인성'));await page.waitForFunction(()=>document.getElementById('requestStaff').dataset.loaded==='true');assert.equal(await page.locator('#requestStaff').inputValue(),'인성');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));
await page.locator('#requestName').fill('신청 고객');await page.locator('#requestPhone').pressSequentially('01011112222');assert.equal(await page.locator('#requestPhone').inputValue(),'010-1111-2222');await page.evaluate(()=>submitConsultationRequest());assert.match(await page.locator('#requestMessage').textContent(),/서비스/);await page.locator('input[name=service][value=휴대폰]').check();await page.evaluate(()=>submitConsultationRequest());assert.match(await page.locator('#requestMessage').textContent(),/동의/);
await page.locator('#requestConsent').check();await page.locator('#requestNote').fill('아이폰 조건 문의');const key=await page.evaluate(()=>requestKey);await page.evaluate(()=>{window.__failNext=true;return submitConsultationRequest()});assert(!(await page.locator('#requestSubmit').isDisabled()));assert.equal(await page.evaluate(()=>requestKey),key);await page.locator('#requestSubmit').click();await page.waitForFunction(()=>document.getElementById('requestMessage').classList.contains('success'));const publicWrite=await page.evaluate(()=>window.__writes.at(-1).payload);assert.equal(publicWrite.staff_name,'인성');assert.equal(publicWrite.phone_digits,'01011112222');assert.equal(publicWrite.privacy_consent,true);assert(!('status' in publicWrite));assert(!('consultation_note' in publicWrite));assert(await page.locator('#requestSubmit').isDisabled());await page.evaluate(()=>submitConsultationRequest());assert.equal(await page.evaluate(()=>window.__db.length),1);
await page.screenshot({path:path.join(output,'jk-consultation-request-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: consultation syntax, staff tabs/search/pagination, XSS escaping, create/edit/draft/phone, due-date auto-calculation, contact history/reschedule, close/reopen/conflict, separate reminders, mobile/back, public form consent/retry/staff routing/duplicate click guard');
})().catch(e=>{console.error(e);process.exit(1)});
