const assert=require('assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const {financeCompute,financeShiftMonth,financeMonthEnd}=require('../business-finance.js');
const item=(item_key,category,direction,amount,due_date,extra={})=>({item_key,category,direction,amount,due_date,title:item_key,source_month:'2026-09-01',basis:{},payroll_tax_mode:'none',confirmed:false,excluded:false,...extra});
const data={snapshot:{snapshot_date:'2026-10-02',total_balance:1000000,tax_reserve_target:200000,tax_reserve_saved:100000,minimum_buffer:50000,tax_reserve_configured:true,updated_at:'2026-10-02T01:00:00Z'},items:[item('vendor','vendor','out',764000,'2026-10-31',{basis:{margin:236000,received:1000000}}),item('salary','payroll','out',94400,'2026-10-31',{basis:{margin:236000,rate:40}}),item('card','card','in',970000,'2026-11-05'),item('expense','expense','out',100000,'2026-11-20'),item('unknown','expense','out',999999,'2026-09-30')],payments:[],invoices:[{invoice_date:'2026-10-01',kind:'sales',vat_amount:100000},{invoice_date:'2026-10-01',kind:'purchase',vat_amount:30000,creditable:true},{invoice_date:'2026-10-01',kind:'purchase',vat_amount:40000,creditable:false},{invoice_date:'2026-10-01',kind:'sales',vat_amount:999999,voided:true}]};
let m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.current,1000000);assert.equal(m.free,800000);assert.equal(m.endCash,141600);assert.equal(m.nextCash,1011600);assert.equal(m.nextFree,811600);assert.equal(m.vatReference,70000);assert.equal(m.unknown.length,1);assert.equal(m.salary[0].amount,94400);
assert.equal(financeShiftMonth('2026-12',1),'2027-01');assert.equal(financeMonthEnd('2028-02'),'2028-02-29');
const paid={id:'pay',item_key:'vendor',amount:300000,paid_on:'2026-10-02',created_at:'2026-10-02T02:00:00Z',balance_included:false};data.payments=[paid];m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.current,700000);assert.equal(m.itemMap.vendor.remaining,464000);assert.equal(m.endCash,141600);assert.equal(m.actualOut,300000);
paid.balance_included=true;m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.current,1000000);assert.equal(m.endCash,441600);
paid.balance_included=false;data.snapshot.updated_at='2026-10-02T03:00:00Z';assert.equal(financeCompute(data,'2026-10-02','2026-10').current,1000000);
paid.voided=true;m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.itemMap.vendor.remaining,764000);assert.equal(m.actualOut,0);
paid.voided=false;paid.paid_on='2026-10-01';assert.equal(financeCompute(data,'2026-10-02','2026-10').current,1000000);
data.items.find(r=>r.item_key==='unknown').confirmed=true;m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.unknown.length,0);assert.equal(m.endCash,441600-999999);
data.items.find(r=>r.item_key==='unknown').excluded=true;data.items.find(r=>r.item_key==='card').basis.settled_on='2026-09-30';m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.nextTotals.incoming,0);assert.equal(m.nextCash,341600);assert.equal(m.nextFree,141600);
// Inbound payments and voided payments are counted once; taxes saved are a subset of cash.
data.payments.push({item_key:'card',amount:100000,paid_on:'2026-10-02',created_at:'2026-10-02T04:00:00Z'});m=financeCompute(data,'2026-10-02','2026-10');assert.equal(m.current,1100000);assert.equal(m.actualIn,100000);assert.equal(m.free,900000);
console.log('PASS: signed W-S, no S double-count, partial payment/current cash, old/new checkpoint inclusion, historical/voided payments, tax reserve once, invoice eligibility, overdue confirmation, native settled card, month/year/leap boundaries');

const {chromium}=require('playwright');const repo=path.join(__dirname,'..');
const stub=String.raw`
window.__writes=[];window.__finance={snapshot:null,items:[],payments:[],invoices:[],ledger_vat:0};window.__fail=false;window.__delay=0;
function query(table){let op='select',payload,filters=[];const q=new Proxy({}, {get:(t,k)=>{if(k==='then')return async resolve=>{await new Promise(r=>setTimeout(r,__delay));let rows=table==='jk_internal_items'?__finance.items:table==='jk_internal_tax_invoices'?__finance.invoices:[];if(op==='upsert'&&table==='jk_internal_balances'){__finance.snapshot={id:'balance',...payload,updated_at:new Date().toISOString()};__writes.push({table,op,payload});return resolve({data:__finance.snapshot,error:null})}if(op==='insert'){const r={...payload,id:crypto.randomUUID(),confirmed:true,updated_at:new Date().toISOString(),basis:{}};const previous=table==='jk_internal_items'?rows.find(x=>x.item_key===r.item_key):null;if(previous){Object.assign(previous,r,{basis:previous.basis});}else rows.push(r);__writes.push({table,op,payload});return resolve({data:r,error:null})}if(op==='update'){const r=rows.find(r=>filters.every(f=>f(r)));if(!r)return resolve({data:null,error:{code:'PGRST116',message:'conflict'}});Object.assign(r,payload,{updated_at:new Date().toISOString(),confirmed:true});__writes.push({table,op,payload});return resolve({data:r,error:null})}return resolve({data:[],error:null});};return (...a)=>{if(['insert','upsert','update'].includes(k)){op=k;payload=a[0]}if(k==='eq')filters.push(r=>r[a[0]]===a[1]);return q;};}});return q;}
window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>{}},from:query,rpc:async(name,p)=>{await new Promise(r=>setTimeout(r,__delay));if(name==='jk_internal_settlement_data')return {data:JSON.parse(JSON.stringify(__finance)),error:null};if(name==='jk_internal_record_payment'){__writes.push({name,p});if(__fail){__fail=false;return {error:{message:'network'}}}if(!__finance.payments.some(x=>x.request_key===p.p_request_key))__finance.payments.push({id:crypto.randomUUID(),request_key:p.p_request_key,item_key:p.p_item_key,paid_on:p.p_paid_on,amount:p.p_amount,payment_method:p.p_payment_method,balance_included:p.p_balance_included,note:p.p_note,created_at:new Date().toISOString()});return {data:'pay',error:null}}if(name==='jk_internal_void_payment'){__finance.payments.find(x=>x.id===p.p_id).voided=true;return {error:null}}return {data:null,error:null}}})};`;
(async()=>{new vm.Script(stub);for(const f of ['business-center.html','business-app/index.html'])for(const s of fs.readFileSync(path.join(repo,f),'utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))if(s[1].trim())new vm.Script(s[1]);
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1400,height:980},timezoneId:'Asia/Seoul'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept('테스트 오입력 취소'));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.href.includes('supabase-js'))return route.fulfill({contentType:'application/javascript',body:stub});const f=path.join(repo,u.pathname.slice(1));if(u.hostname==='finance.test'&&fs.existsSync(f)&&fs.statSync(f).isFile())return route.fulfill({contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(f,'utf8')});return route.fulfill({status:404,body:''})});
 await page.goto('https://finance.test/business-center.html?balance=1000000');await page.evaluate(async()=>{hideLogin();const today=financeToday(),month=today.slice(0,7),prev=financeShiftMonth(month,-1),next=financeShiftMonth(month,1);__finance.items=[{item_key:'vendor-test',category:'vendor',title:'<img src=x onerror=alert(1)>',source_month:prev+'-01',direction:'out',amount:764000,due_date:financeMonthEnd(month),confirmed:false,excluded:false,basis:{margin:236000,received:1000000,formula:'W-S'}},{item_key:'salary-test',category:'payroll',payroll_tax_mode:'none',title:'송훈 급여',source_month:prev+'-01',direction:'out',amount:94400,due_date:financeMonthEnd(month),confirmed:false,excluded:false,basis:{margin:236000,rate:40,staff_name:'송훈',formula:'W × 급여율'}},{item_key:'card-test',category:'card',title:'카드 예정',source_month:month+'-01',direction:'in',amount:970000,due_date:next+'-05',confirmed:false,excluded:false,basis:{}},{item_key:'old-test',category:'expense',title:'과거 미확인',source_month:prev+'-01',direction:'out',amount:999999,due_date:prev+'-01',confirmed:false,excluded:false,basis:{}}];go('finance');await loadInternalFinance()});
 assert.equal(await page.locator('#financeCurrent').textContent(),'1,000,000원');assert.match(await page.locator('#financeWarnings').textContent(),/임시 계산/);assert.equal(await page.locator('#financeItems img').count(),0);assert.match(await page.locator('#financeSalaryRows').textContent(),/40%/);assert.equal(await page.locator('#financeNextIn').textContent(),'970,000원');
 await page.getByRole('button',{name:'잔고 / 세금 기준 입력'}).click();assert.equal(await page.locator('#fiTotal').inputValue(),'1000000');await page.locator('#fiTaxTarget').fill('200000');await page.locator('#fiTaxSaved').fill('100000');await page.locator('#modalSave').click();await page.waitForFunction(()=>financeState.data.snapshot&&!financeState.data.snapshot.draft);assert.equal(await page.locator('#financeFree').textContent(),'800,000원');assert(!/임시 계산/.test(await page.locator('#financeWarnings').textContent()));
 await page.evaluate(()=>openFinanceItem('vendor-test'));await page.getByRole('button',{name:'확정 후 실제 지급 기록'}).click();await page.waitForSelector('#fiPaidAmount');await page.locator('#fiPaidAmount').fill('300000');await page.locator('#fiIncluded').check();await page.locator('#fiPaymentNote').fill('거래처 일부 지급');await page.evaluate(()=>{__delay=30;saveModal();saveModal()});await page.waitForFunction(()=>__finance.payments.length===1);await page.waitForFunction(()=>financeState.model.itemMap['vendor-test'].remaining===464000);assert.equal(await page.locator('#financeCurrent').textContent(),'1,000,000원');assert.equal(await page.locator('#financeEnd').textContent(),'441,600원');assert.match(await page.locator('#financeHistory').textContent(),/300,000원/);assert.equal(await page.evaluate(()=>__writes.filter(w=>w.name==='jk_internal_record_payment').length),1);
 await page.locator('[data-payment-void]').click();await page.waitForFunction(()=>financeState.model.itemMap['vendor-test'].remaining===764000);assert.equal(await page.locator('#financeActualOut').textContent(),'0원');
 await page.locator('#financeFilter').selectOption('unknown');assert.match(await page.locator('#financeItems').textContent(),/과거 미확인/);
 await page.getByRole('button',{name:'계산서 기록',exact:true}).click();await page.locator('#fiInvoiceVendor').fill('거래처');await page.locator('#fiSupply').fill('700000');await page.locator('#fiVAT').fill('70000');await page.locator('#fiCreditable').check();await page.locator('#modalSave').click();await page.waitForFunction(()=>financeState.model.purchaseVat===70000);assert.equal(await page.locator('#financePurchaseVAT').textContent(),'70,000원');assert.match(await page.locator('#financeInvoices').textContent(),/매입/);
 await page.getByRole('button',{name:'기타 / 세금 예정 추가'}).click();await page.locator('#fiTitle').fill('부가세 예정');await page.locator('#fiCategory').selectOption('tax');await page.locator('#fiAmount').fill('50000');await page.locator('#modalSave').click();await page.waitForFunction(()=>financeState.model.items.some(r=>r.category==='tax'));await page.locator('#financeFilter').selectOption('tax');assert.match(await page.locator('#financeItems').textContent(),/부가세 예정/);
 const out=process.env.TEST_OUTPUT_DIR||require('os').tmpdir();await page.screenshot({path:path.join(out,'jk-internal-finance-desktop.png'),fullPage:true});
 for(const width of [360,390,768]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await page.evaluate(()=>openFinanceBalance());assert(await page.locator('#fiTotal').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await page.evaluate(()=>closeModal());}await page.screenshot({path:path.join(out,'jk-internal-finance-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: finance navigation, balance draft/save, tax goal, W-S direction, payroll rule, partial payment/duplicate guard/void, invoice recording, manual tax item, XSS escaping, mobile 360/390/768px');
})().catch(e=>{console.error(e);process.exit(1)});
